name: Release Fide Entity Vocabulary

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  deployments: write

jobs:
  publish-fide-vocabulary:
    permissions:
      contents: write
      id-token: write
      deployments: write
    uses: fide/lally-workflows/.github/workflows/release-publish.yml@main
    with:
      tag_prefix: "v"
      install_working_directory: "sdk/javascript"
      package_dir: "sdk/javascript"
      deployment_environment: "Preview - vocabulary"
