name: Release Fide Entity Vocabulary

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  deployments: write

jobs:
  publish-fide-vocabulary:
    permissions:
      contents: write
      id-token: write
      deployments: write
    uses: ChrisLally/lally-workflows/.github/workflows/npm-publish-release.yml@beeaf5a5511d1270b571b3be1f0485c203b952fa
    with:
      tag_prefix: "v"
      install_working_directory: "sdk/javascript"
      package_dir: "sdk/javascript"
      deployment_environment: "Preview - vocabulary"
